# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_text_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='text',
            new_name='content',
        ),
    ]
