# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170717_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=None, upload_to='videos'),
        ),
    ]
