# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170720_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(default='localhost', upload_to='videos'),
        ),
    ]
