# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
